name: Render Report

on:
  push:
    paths: ["analysis/**", "scripts/**", "data/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2
    - name: Install packages
      run: Rscript -e 'install.packages(c("tidyverse","rmarkdown","renv")); renv::restore()'
    - name: Render
      run: Rscript -e 'rmarkdown::render("analysis/report.Rmd")'
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: report
        path: analysis/report.html